# Generated by Django 4.2.2 on 2023-08-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.CharField(choices=[('KU', 'Kenyatta University'), ('JKUAT', 'Jomo Kenyatta Univeristy Of Agriculture and Technology'), ('TUK', 'Technical University of Kenya'), ('UON', 'University Of Nairobi'), ('TUM', 'Technical University of Mombasa'), ('DeKUT', 'Dedan Kimathi University of Technology')], max_length=100),
        ),
    ]
